# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=inventario_db1;encrypt=true;trustServerCertificate=true
spring.datasource.username=usuario-pyme1
spring.datasource.password=Pyme1234*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# App Configuration
server.port=8080
spring.application.name=inventario-pyme
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Logging para seguridad
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.core=TRACE
logging.level.com.pymes.inventario=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daryanhemmings@gmail.com
spring.mail.password=bbww pszj hyzm pywj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


